---
- hosts: all
  remote_user: vagrant
  become: yes
  tasks:

  - name: Add Mesosphere Repository
    yum:
      name: http://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-3.noarch.rpm
      state: present

  - name: Install mesos
    yum:
      name: mesos
      state: present
  
  - name: Install mesosphere-zookeeper
    yum:
      name: mesosphere-zookeeper
      state: present

  - name: Install marathon
    yum:
      name: marathon
      state: present

  - name: Install chronos
    yum:
      name: chronos
      state: present

  - name: Change Hostname to 'mesos'
    hostname:
      name: mesos

# Reboot and wait for server to return
  - name: Reboot the server and wait for it to come back up.
    reboot:

...
